### ISSUE TITLE
Missing mount point in "invalid_verification_link.html"

### ISSUE THREAD

**Issue by Gitzoz** [parse-community/parse-server#3857]
Hello everyone, 
on the invalid_verification_link page the button to resend verification email 
has a wrong url. It gets the appId from the given url but not the mount point. 

It has: https://xxxx/app/{appId}/resend_verification_email
it should have: https://xxxx/{mountpoint}/app/{appId}/resend_verification_email

In my ParseServer config I have set the publicServerURL correct. Everything else works fine.

ParseServer Version: 2.4.1
Procedure: Open a invalid verification link and click on the button "Resend Link"

Hope that helps

Best regards
Gitzoz

**Comment by funkenstrahlen** [comment]
I am running the current parse server version `2.5.3`. I see the exact same problem.

**Comment by funkenstrahlen** [comment]
This script creates the resend verification link. It obviously ignores mount point.

```html
  <script type="text/javascript">
    function getUrlParameter(name) {
      name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
      var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
      var results = regex.exec(location.search);
      return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
    };  
    window.onload = addDataToForm;
    function addDataToForm() {
      var username = getUrlParameter("username");
      document.getElementById("usernameField").value = username;
      var appId = getUrlParameter("appId");
      document.getElementById("resendForm").action = '/apps/' + appId + '/resend_verification_email'
    }
  </script>
```

**Comment by funkenstrahlen** [comment]
@flovilmart Is there any way to make this html response more dynamic so we can pass parameters into this file like `appId` and `serverUrl`?

I think the current approach to work with regex on the url is not very reliable and ready for future changes.

**Comment by flovilmart** [comment]
Yes you’re right, it’s bound to be problematic. Do you wanna take a dent at it? I would be ok with simple templating for rendering those pages.

**Comment by funkenstrahlen** [comment]
This is still an issue.

**Comment by flovilmart** [comment]
@funkenstrahlen are you willing to make a PR for it? Obviously this should be fixed. What bugs me is that all other pages are fine right?

**Comment by tommylindgren-plejd** [comment]
This is still an issue in parse-server 4.5.0. The url do now reflect the pages endpoint. Related Issue: 
https://github.com/parse-community/parse-server/issues/7235
https://github.com/parse-community/parse-server/pull/7236
